In [35]:
import tensorflow as tf

In [36]:
a = tf.constant(2)
b = tf.constant(3)

In [47]:
x = tf.add(a, b)
print(x)

Tensor("Add_2:0", shape=(), dtype=int32)


In [42]:
# Session은 대문자이므로 sess 객체생성임
sess = tf.Session()
x_value = sess.run(x)
sess.close()

In [43]:
with tf.Session() as sess:
    x_value = sess.run(x)

In [51]:
x =tf.random_normal([3], mean=0.0, stddev=1.0, dtype=tf.float32)

sess = tf.Session()
x_value = sess.run(x)
print(x_value)
sess.close()

[-2.0601182   0.06327873 -0.10457092]


In [54]:
x = tf.truncated_normal([3], mean=0.0, stddev=1.0, dtype=tf.float32)

sess = tf.Session()
x_value2 = sess.run(x)
print(x_value2)
sess.close()

[ 0.43630588  1.42383313  1.0442524 ]


In [56]:
x = tf.random_uniform([2], minval=1, maxval=7, dtype=tf.int32)

sess = tf.Session()
x_value3 = sess.run(x)
print(x_value3)
sess.close()

[5 1]


In [61]:
a0 = tf.zeros([3,4], tf.int32)
sess = tf.Session()
sess.run(a0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [63]:
a1 = tf.ones([2,3], tf.int32)
sess.run(a1)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [68]:
a = [[1,2,3],[4,5,6]]

x2 = tf.zeros_like(a)
sess = tf.Session()
sess.run(x2)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [69]:
x3 = tf.ones_like(a)
sess.run(x3)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [75]:
sess.run(tf.random_uniform([5], 0.0, 1.0, dtype=tf.float32))

array([ 0.16669428,  0.20453465,  0.30523717,  0.16289449,  0.04731619], dtype=float32)

In [76]:
x5 = tf.random_shuffle([1,2,3,4,5,6])
sess.run(x5)

array([2, 4, 6, 3, 5, 1], dtype=int32)

In [78]:
x6 = tf.random_shuffle([[1,2],[3,4],[5,6]])
sess.run(x6)

array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)

In [82]:
# tensorflow Operations 
A = tf.constant([3,6])
B = tf.constant([2,2])

X7 = tf.add(A,B)
sess.run(X7)


array([ 6, 12], dtype=int32)

In [83]:
X8 = tf.multiply(A,B)
sess.run(X8)

array([ 6, 12], dtype=int32)

In [86]:
#X9 = tf.matmul(A,B)
#sess.run(X9)

In [88]:
sess.run(tf.reshape(B, [2,1]))

array([[2],
       [2]], dtype=int32)

In [92]:
X9 = tf.matmul(tf.reshape(A, [1,2]), tf.reshape(B, [2,1]))
sess.run(X9)

array([[18]], dtype=int32)

In [93]:
T1 = [[1,2,3],[4,5,6]]
T2 = [[7,8,9],[10,11,12]]

X1 = tf.concat([T1,T2], axis=0)
sess.run(X1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [94]:
X1 = tf.concat([T1,T2], axis=1)
sess.run(X1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)

In [95]:
w = tf.Variable(0, name='w')

init_op = tf.global_variables_initializer()
sess.run(init_op)
sess.run(w)

0

In [97]:
sess.run(init_op)
sess.run(w)

0

In [98]:
assign10_op = w.assign(10)
sess.run(w)

0

In [99]:
sess.run(assign10_op)
sess.run(w)

10

In [101]:
w = tf.Variable(0, name='w')
assign10_op = w.assign(10)

init_op = tf.global_variables_initializer()

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(init_op)
sess2.run(init_op)

In [103]:
sess1.run(assign10_op)
sess1.run(w)

10

In [104]:
sess2.run(w)

0

In [106]:
# Placeholder FeedDict
input = tf.placeholder(tf.float32, shape=[2], name='my_input')
y = input + 1
sess.run(y, feed_dict={input:[2,2]})

array([ 3.,  3.], dtype=float32)